# frozen_string_literal: true
source 'http://rubygems.org'

ruby '3.1.2'

gem 'sinatra'
gem 'activerecord', '~> 5.2'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'i18n'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'faker'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
end
